# -*- coding: utf-8 -*-
"""Assignment1_2602182865_AlviAuliaFatikha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DimaCVhiwb9nMlOhxVsTOfzIuGaPFo-g

Alvi Aulia Fatikha (2602182865)
No 1
"""

def isDDM(m, n):
  for i in range (0, n):
    sum = 0
    for j in range(0, n):
      sum = sum + abs (m[i][j])
    sum = sum - abs(m[i][i])
    if(abs(m[i][i])<sum):
      return False
    return True

n = 3
m = [[8, 3, -4],
    [5, 10, -2],
    [-1, 1, 3]]

if((isDDM(m, n))):
    print ("Diagonally dominant.")
else:
    print ("Error!")

f1 = lambda x,y,z: (10-3*y+4*z)/8
f2 = lambda x,y,z: (5-5*x+2*z)/10
f3 = lambda x,y,z: (9+x-y)/3

x0 = 0
y0 = 0
z0 = 0
count = 1

e = float(input('Enter tolerable error: '))

print('\nCount\tx\ty\tz\n')

condition = True

while condition:
    x1 = f1(x0,y0,z0)
    y1 = f2(x1,y0,z0)
    z1 = f3(x1,y1,z0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
    e1 = abs(x0-x1);
    e2 = abs(y0-y1);
    e3 = abs(z0-z1);

    count += 1
    x0 = x1
    y0 = y1
    z0 = z1

    condition = e1>e and e2>e and e3>e

print('\nSolution: x = %0.3f, y = %0.3f and z = %0.3f\n'% (x1,y1,z1))

def isDDM(m, n):
  for i in range (0, n):
    sum = 0
    for j in range(0, n):
      sum = sum + abs (m[i][j])
    sum = sum - abs(m[i][i])
    if(abs(m[i][i])<sum):
      return False
    return True

n = 3
m = [[7, 2, -1],
    [3, 5, 4],
    [-2, -4, 9]]


if((isDDM(m, n))):
    print ("Diagonally dominant.")
else:
    print ("Error!")

f1 = lambda x,y,z: (5-2*y+z)/7
f2 = lambda x,y,z: (7-3*x-4*z)/5
f3 = lambda x,y,z: (4+2*x+4*y)/9

x0 = 0
y0 = 0
z0 = 0
count = 1

e = float(input('Enter tolerable error: '))

print('\nCount\tx\ty\tz\n')

condition = True

while condition:
    x1 = f1(x0,y0,z0)
    y1 = f2(x1,y0,z0)
    z1 = f3(x1,y1,z0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
    e1 = abs(x0-x1);
    e2 = abs(y0-y1);
    e3 = abs(z0-z1);

    count += 1
    x0 = x1
    y0 = y1
    z0 = z1

    condition = e1>e and e2>e and e3>e

print('\nSolution: x = %0.3f, y = %0.3f and z = %0.3f\n'% (x1,y1,z1))

"""Alvi Aulia Fatikha (2602182865)
No 2
"""

from scipy.interpolate import interp1d
import matplotlib.pyplot as plt

plt.style.use('seaborn-poster')
x = [-3, 0, 3, 6, 9, 12, 15, 18, 21, 24]
y = [4, 7, 11, 16, 22, 29, 38, 49, 63, 80]

f = interp1d(x,y)
y_hat = f(16)
print(y_hat)

plt.figure(figsize=(10,8))
plt.plot(x, y, '-ob')
plt.plot(16, y_hat, 'ro')
plt.title('Linear Interpolatian at x = 16')
plt.xlabel('x')
plt.ylabel('y')
plt.show()